In [1]:
from solver import *

In [2]:
# Box Selector
n = 5
np.arange(81).reshape((9,9))[3*floor(n/3):3*floor(n/3)+3, (3*n)%9:(3*n)%9 + 3]

array([[33, 34, 35],
       [42, 43, 44],
       [51, 52, 53]])

In [3]:
np.arange(81).reshape((9,9))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [4]:
sodoku = generate_sodoku()
sodoku

array([[0., 3., 7., 0., 0., 5., 0., 6., 9.],
       [5., 0., 8., 4., 0., 6., 0., 0., 1.],
       [4., 9., 1., 3., 0., 0., 8., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 8., 0.],
       [3., 0., 0., 0., 0., 4., 0., 0., 5.],
       [0., 0., 0., 0., 1., 0., 0., 2., 4.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 6., 0., 0., 9., 0., 0., 0.],
       [0., 7., 4., 0., 0., 0., 0., 9., 0.]])

In [5]:
solver(sodoku)

0 {8, 1, 2}
3 set()
3 {2}
4 set()
4 {4}
6 set()
6 {1}
10 set()
10 {2}
13 set()
13 {9, 3, 7}
15 set()
15 {7}
16 set()
16 {3}
22 set()
22 {2, 5, 6, 7}
23 set()
23 {7}
25 set()
25 {5}
26 set()
26 {6}
27 set()
27 {1, 2, 6, 7, 9}
28 set()
28 {4, 5, 6}
29 set()
29 {9, 2, 5}
30 set()
30 {5, 6, 7}
31 set()
31 {6, 7}
32 set()
32 {2}
35 set()
35 {7}
37 set()
37 {8, 6}
38 set()
38 {2}
39 set()
39 {9, 6, 7}
40 set()
40 {7}
42 set()
42 {6}
43 set()
43 {1}
45 set()
45 {9, 6, 7}
46 set()
46 {5, 6}
47 set()
47 {3}
48 set()
48 {8, 6, 7}
50 set()
50 set()
48 {6, 7}
48 {6, 7}
50 set()
50 {8}
51 set()
51 set()
48 {7}
48 {7}
50 set()
50 set()
46 {6}
46 {6}
47 set()
47 {5}
48 set()
48 set()
45 {6, 7}
45 {6, 7}
46 set()
46 set()
45 {7}
45 {7}
46 set()
46 set()
39 {6, 7}
39 {6, 7}
40 set()
40 set()
39 {7}
39 {7}
40 set()
40 set()
37 {6}
37 {6}
38 set()
38 set()
31 {7}
31 {7}
32 set()
32 set()
30 {6, 7}
30 {6, 7}
31 set()
31 {5}
32 set()
32 set()
30 {7}
30 {7}
31 set()
31 {6}
32 set()
32 set()
29 {2, 5}
29 {2,

KeyboardInterrupt: 