In [6]:
from solver import *

In [7]:
# Box Selector
n = 5
np.arange(81).reshape((9,9))[3*floor(n/3):3*floor(n/3)+3, (3*n)%9:(3*n)%9 + 3]

array([[33, 34, 35],
       [42, 43, 44],
       [51, 52, 53]])

In [8]:
np.arange(81).reshape((9,9))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [9]:
sodoku = generate_sodoku()
sodoku

array([[0., 6., 0., 0., 0., 2., 5., 3., 0.],
       [8., 0., 0., 5., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 8., 0., 0.],
       [0., 7., 0., 4., 6., 5., 3., 2., 9.],
       [0., 0., 9., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 8., 1.],
       [6., 0., 0., 0., 3., 1., 0., 0., 0.],
       [0., 0., 0., 6., 9., 7., 0., 5., 0.],
       [2., 0., 0., 0., 5., 0., 4., 0., 0.]])

In [10]:
solver(sodoku)

{0: {4, 9, 7}, 2: set(), 3: set(), 4: set(), 8: set(), 10: set(), 11: set(), 13: set(), 14: set(), 15: set(), 17: set(), 18: set(), 19: set(), 20: set(), 21: set(), 23: set(), 25: set(), 26: set(), 27: set(), 29: set(), 36: set(), 37: set(), 39: set(), 40: set(), 41: set(), 43: set(), 44: set(), 45: set(), 46: set(), 47: set(), 48: set(), 49: set(), 50: set(), 51: set(), 55: set(), 56: set(), 57: set(), 60: set(), 61: set(), 62: set(), 63: set(), 64: set(), 65: set(), 69: set(), 71: set(), 73: set(), 74: set(), 75: set(), 77: set(), 79: set(), 80: set()}
{0: {4, 9, 7}, 2: {4, 7}, 3: set(), 4: set(), 8: set(), 10: set(), 11: set(), 13: set(), 14: set(), 15: set(), 17: set(), 18: set(), 19: set(), 20: set(), 21: set(), 23: set(), 25: set(), 26: set(), 27: set(), 29: set(), 36: set(), 37: set(), 39: set(), 40: set(), 41: set(), 43: set(), 44: set(), 45: set(), 46: set(), 47: set(), 48: set(), 49: set(), 50: set(), 51: set(), 55: set(), 56: set(), 57: set(), 60: set(), 61: set(), 62: set()

KeyboardInterrupt: 