In [1]:
from solver import *

In [2]:
# Box Selector
n = 5
np.arange(81).reshape((9,9))[3*floor(n/3):3*floor(n/3)+3, (3*n)%9:(3*n)%9 + 3]

array([[33, 34, 35],
       [42, 43, 44],
       [51, 52, 53]])

In [3]:
np.arange(81).reshape((9,9))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [7]:
sodoku = generate_sodoku()
sodoku

array([[0., 0., 0., 0., 0., 0., 0., 0., 3.],
       [0., 0., 0., 0., 0., 6., 9., 0., 0.],
       [0., 2., 0., 0., 9., 0., 0., 0., 4.],
       [2., 3., 0., 0., 0., 9., 0., 0., 0.],
       [0., 6., 8., 0., 2., 0., 3., 7., 0.],
       [0., 9., 1., 0., 3., 0., 0., 4., 5.],
       [0., 7., 6., 8., 0., 0., 0., 5., 0.],
       [8., 1., 3., 0., 0., 4., 6., 9., 0.],
       [5., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
solver(sodoku)

array([[1., 8., 9., 5., 4., 2., 7., 6., 3.],
       [3., 5., 4., 7., 8., 6., 9., 2., 1.],
       [6., 2., 7., 3., 9., 1., 5., 8., 4.],
       [2., 3., 5., 4., 7., 9., 8., 1., 6.],
       [4., 6., 8., 1., 2., 5., 3., 7., 9.],
       [7., 9., 1., 6., 3., 8., 2., 4., 5.],
       [9., 7., 6., 8., 1., 3., 4., 5., 2.],
       [8., 1., 3., 2., 5., 4., 6., 9., 7.],
       [5., 4., 2., 9., 6., 7., 1., 3., 8.]])