In [1]:
from generator import *

In [2]:
# Box Selector
n = 5
np.arange(81).reshape((9,9))[3*floor(n/3):3*floor(n/3)+3, (3*n)%9:(3*n)%9 + 3]

array([[33, 34, 35],
       [42, 43, 44],
       [51, 52, 53]])

In [3]:
np.arange(81).reshape((9,9))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [4]:
generate_sodoku()

array([[0., 5., 4., 1., 9., 0., 2., 0., 7.],
       [0., 2., 6., 0., 7., 0., 0., 0., 0.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0.],
       [4., 0., 8., 0., 0., 0., 0., 0., 0.],
       [6., 9., 2., 0., 1., 0., 7., 0., 0.],
       [0., 0., 7., 0., 3., 2., 0., 0., 0.],
       [1., 0., 5., 0., 0., 3., 0., 0., 0.],
       [0., 4., 9., 7., 0., 0., 0., 0., 8.],
       [0., 0., 3., 0., 5., 0., 0., 2., 0.]])